### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrayson** [mrayson/so_iwaves#1]
- [x] Collate code into this repository
- [x] PSD of imos deep mooring sites
- [x] Maps of MIOST and HRET internal tides
- [ ] Predictions of internal tide (SSH) at 2 sites (ITF and SOTS)
- [x] Density stratification at 2 sites from CARS (summer and winter)
- [ ] Mode-1 amplitude estimate using CARS density
- [x] non-phase locked IT overview
- [x] KdV runs and animations
- [ ] #4
- [ ] SSH from idealised SUNTANS runs

## Aspirational
- [x] #2
- [x] #3
- [x] Idealised 2D suntans to show effect of vertical stratification
